env:
  global:
    - HUGO_VERSION="0.68.3"

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xzvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin
  - hugo version

script:
  - hugo --gc --minify

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  keep-history: false
  on:
    branch: master
