baseurl = "https://tarquin-the-brave.github.io/blog/"
title = "tarquin-the-brave"
copyright = "Copyright &copy; 2020 - Tom Steavenson"
canonifyurls = true
theme = "hugo-coder"
publishDir = "docs"
staticDir = ["static"]

[pagination]
  pagerSize = 300

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
googleAnalytics = "UA-161243400-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 1

[params]
  author = "Tom Steavenson"
  description = ""
  info = ["Some things I think."]
  colorScheme = "auto"
  customJS  = ["js/copy-code.js"]
  customCSS = ["css/copy-code.css"]

  [params.utterances]
    repo = "tarquin-the-brave/blog"
    issueTerm = "pathname"

[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tarquin-the-brave"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 2
  url = "index.xml"
