baseurl = "https://tarquin-the-brave.github.io/blog/"
title = "tarquin-the-brave"
copyright = "Copyright &copy; 2020 - Tom Steavenson"
canonifyurls = true
theme = "hugo-kiera"
publishDir = "docs"

paginate = 100

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
googleAnalytics = "UA-161243400-1"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Tom Steavenson"
    github = "tarquin-the-brave"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    #twitter = "ds_says"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname

[params]
    tagline = "Some things I think.\n\n[**--- All Posts ---**](./posts/)"
    description = ""
    utterancesRepo = "tarquin-the-brave/blog"
    utterancesIssueTerm = "pathname"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""

# uncomment to enable the Tags link on the main toolbar
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 1

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 1
